/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TmTw6PnSAwV
 */
import Link from "next/link"

export function herosection() {
  return (
    <section className="w-full pt-12 md:pt-24 lg:pt-32 bg-gradient-to-r from-pink-200 via-purple-200 to-blue-200">
      <div className="container mx-auto px-4 md:px-6 lg:px-8 grid gap-8 md:grid-cols-2 items-center">
        <div className="space-y-6">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-800">WelcomeHER</h1>
          <p className="text-lg md:text-xl lg:text-2xl text-gray-700">
            Moving from another country? Figure out what you need to know!
          </p>
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 text-white px-6 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-600"
            href="#"
          >
            Try now
          </Link>
        </div>
        <div>
          <img
            alt="Placeholder"
            className="mx-auto aspect-[1/1] overflow-hidden rounded-xl object-cover"
            height="500"
            src="/placeholder.svg"
            width="500"
          />
        </div>
      </div>
    </section>
  )
}
