/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/34aIPcLPe9R
 */
import Link from "next/link"

export function hero1() {
  return (
    <section className="w-full h-screen flex flex-col items-center justify-center bg-gradient-to-r from-[#FFC1E3] to-[#FFB6C1] dark:from-[#6B3E26] dark:to-[#8B4513]">
      <h1 className="text-5xl md:text-6xl font-bold text-center text-[#DDA0DD] dark:text-[#FFD700]">WelcomeHER</h1>
      <p className="mt-4 text-xl md:text-2xl text-center text-gray-700 dark:text-gray-300">
        Moving from another country? Figure out what you need to know.
      </p>
      <div className="mt-8 w-full max-w-md">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="country">
          What country are you moving from?
        </label>
        <select
          className="mt-1 block w-full shadow-sm sm:text-sm rounded-md bg-white dark:bg-gray-800"
          id="country"
          name="country"
        >
          <option value="">Select your country</option>
          <option value="usa">USA</option>
          <option value="uk">UK</option>
          <option value="canada">Canada</option>
        </select>
      </div>
      <div className="mt-4 w-full max-w-md">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="language">
          What language do you prefer?
        </label>
        <select
          className="mt-1 block w-full shadow-sm sm:text-sm rounded-md bg-white dark:bg-gray-800"
          id="language"
          name="language"
        >
          <option value="">Select your language</option>
          <option value="english">English</option>
          <option value="spanish">Spanish</option>
          <option value="french">French</option>
        </select>
      </div>
      <Link
        className="mt-8 inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-[#DDA0DD] hover:bg-[#EE82EE]"
        href="#"
      >
        Try me
      </Link>
    </section>
  )
}
